### PR TITLE
Letter casing bitflags fix

### LINKED ISSUE #473: letter casing incorrect when FlagsAttribute Enum with multiple OR'd items is humanized
**Steps to replicate the issue:**

* Create a bitfield enum using the [FlagsAttribute](https://msdn.microsoft.com/en-us/library/system.flagsattribute(v=vs.110).aspx)
* Add the [DescriptionAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.descriptionattribute(v=vs.110).aspx) to the enum properties
* Create an instance of the enum by OR'ing together a few enum values
* Call `.Humanize()` on the instance and note that the resulting comma separate string is all in caps. 

```C#
    class Program
    {
        [Flags]
        private enum Colors : int
        {
            [Description("None")]
            NONE = 0,
            [Description("Red")]
            RED = 1,
            [Description("Green")]
            GREEN = 2,
            [Description("Blue")]
            BLUE = 4,
            [Description("Greenish Yellow")]
            GREENISH_YELLOW = 8
        }

        static void Main(string[] args)
        {
            Colors multipleColors = Colors.GREENISH_YELLOW | Colors.BLUE | Colors.RED;
            Colors singleColor = Colors.RED;

            // CORRECT
            // Expected: "Red"
            // Actual: "Red"
            Console.WriteLine(singleColor.Humanize());

            // INCORRECT
            // Expected: "Red, Blue, Greenish Yellow"
            // Actual: "RED, BLUE, GREENISH YELLOW"
            Console.WriteLine(multipleColors.Humanize());

            Console.ReadKey();
        }
    }
```

It looks like the `Description` attribute is only being used if the enum instance maps to a single enum value, i.e. it doesn't work when using an instance creating by OR'ing multiple values together.

Hope the above makes sense.

### PR DESCRIPTION
**Pull request by gavynriebau**
fixes #473

Fix for humanizing bitfield enums which:

* Use the `DescriptionAttribute`
* Don't map to a _single_ enum value because they are created by ORing together multiple values.

Example from #473:
```C#
    class Program
    {
        [Flags]
        private enum Colors : int
        {
            [Description("None")]
            NONE = 0,
            [Description("Red")]
            RED = 1,
            [Description("Green")]
            GREEN = 2,
            [Description("Blue")]
            BLUE = 4,
            [Description("Greenish Yellow")]
            GREENISH_YELLOW = 8
        }

        static void Main(string[] args)
        {
            Colors multipleColors = Colors.GREENISH_YELLOW | Colors.BLUE | Colors.RED;
            Colors singleColor = Colors.RED;

            // CORRECT
            // Expected: "Red"
            // Actual: "Red"
            Console.WriteLine(singleColor.Humanize());

            // INCORRECT
            // Expected: "Red, Blue, Greenish Yellow"
            // Actual: "RED, BLUE, GREENISH YELLOW"
            Console.WriteLine(multipleColors.Humanize());

            Console.ReadKey();
        }
    }
```

### CODE REVIEW

File: src/Humanizer/EnumHumanizeExtensions.cs [hunk 1]
```diff
@@ -23,6 +24,26 @@ public static class EnumHumanizeExtensions
...
+                {
+                    var enumIntValue = (int)enumValue;
+
+                    if ((inputIntValue & enumIntValue) != 0)
+                    {
+                        humanizedEnumValues.Add(EnumHumanizeExtensions.Humanize((Enum)enumValue));
+                    }
+                }
+
+                return String.Join(", ", humanizedEnumValues);
```
Comment (mexx) [inline src/Humanizer/EnumHumanizeExtensions.cs]: Can we use `CollectionHumanizeExtensions` here?
The output of the test would currently change to `Red and Dark Gray` on English locale, but it would be localized.
Note: The test class have to inherit from `AmbientCulture` like `CollectionHumanizeTests` does.

**Comment by gavynriebau** [comment]
Thanks mexx,

I've swapped to using `CollectionHumanizeExtensions` and changed my test class to inherit from `AmbientCulture`.

**Comment by onovotny** [comment]
Is this ready for review?

**Comment by gavynriebau** [comment]
Yes, absolutely

**Comment by onovotny** [comment]
Thanks!

File: src/Humanizer/EnumHumanizeExtensions.cs [hunk 2]
```diff
@@ -37,6 +58,43 @@ public static string Humanize(this Enum input)
...
+            return hasFlagsAttribute && underlyingTypeIsInt;
+        }
+
+        /// <summary>
+        /// Returns true if the given enum instance can map exactly to one of the enum's constants.
+        /// This doesn't always happen when using BitField enums.
+        /// </summary>
+        /// <param name="input">An instance of an enum.</param>
+        /// <returns>True, if the instance maps directly to a single enum property, false if otherwise.</returns>
+        private static bool DirectlyMapsToEnumConstant(Enum input)
```
Comment (hazzik) [inline src/Humanizer/EnumHumanizeExtensions.cs]: A little bit late, but. Shouldn't it be `[Enum.IsDefilend](https://msdn.microsoft.com/en-us/library/system.enum.isdefined(v=vs.110).aspx)`?

Comment (gavynriebau) [inline src/Humanizer/EnumHumanizeExtensions.cs]: @hazzik Thanks, you're right and I learnt something new :+1:
